const $=id=>document.getElementById(id);
const themePreference=window.matchMedia('(prefers-color-scheme: dark)');
let savedTheme=null;
try{savedTheme=localStorage.getItem('xii-theme')}catch{}
function themeIcon(theme){
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 20 20');svg.setAttribute('width','20');svg.setAttribute('height','20');svg.setAttribute('fill','currentColor');svg.setAttribute('aria-hidden','true');
 const path=document.createElementNS(ns,'path');path.setAttribute('d',theme==='dark'?'M9 1h2v3H9zM9 16h2v3H9zM1 9h3v2H1zM16 9h3v2h-3zM3.1 4.5l1.4-1.4 2.1 2.1-1.4 1.4zM13.4 14.8l1.4-1.4 2.1 2.1-1.4 1.4zM3.1 15.5l2.1-2.1 1.4 1.4-2.1 2.1zM13.4 5.2l2.1-2.1 1.4 1.4-2.1 2.1z':'M15.5 14a6 6 0 0 1-8-8 7.2 7.2 0 1 0 8 8Z');svg.append(path);
 if(theme==='dark'){const circle=document.createElementNS(ns,'circle');circle.setAttribute('cx','10');circle.setAttribute('cy','10');circle.setAttribute('r','3.4');svg.append(circle)}return svg;
}
function applyTheme(theme){document.documentElement.dataset.theme=theme;$('theme-toggle').setAttribute('aria-pressed',String(theme==='dark'));$('theme-toggle').setAttribute('aria-label',theme==='dark'?'Ativar tema claro':'Ativar tema escuro');$('theme-icon').replaceChildren(themeIcon(theme));$('theme-label').textContent=theme==='dark'?'Claro':'Escuro'}
applyTheme(['light','dark'].includes(savedTheme)?savedTheme:themePreference.matches?'dark':'light');
$('theme-toggle').onclick=()=>{savedTheme=document.documentElement.dataset.theme==='dark'?'light':'dark';applyTheme(savedTheme);try{localStorage.setItem('xii-theme',savedTheme)}catch{}};
themePreference.addEventListener('change',event=>{if(!savedTheme)applyTheme(event.matches?'dark':'light')});
const activities={XII:'XII de Março',Atleta:'Atleta da XII',Hunter:'Hunter E-sports',TOC:'TOC Caçadores',Pantercats:'Pantercats',Panterada:'Bateria Panterada',EP:'Engenharíadas Paranaense',JIA:'Jogos Interatléticas',Evento:'Evento esportivo',Social:'Ação social'};
let records=[],current=null,previewUrl=null,downloadUrl=null,busy=false;
const today=new Date();$('issued').value=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
for(const [value,text] of Object.entries(activities)){const option=new Option(text,value);$('edit-activity').add(option)}
function toast(text,action,label='Desfazer'){const box=$('toast');box.textContent=text;if(action){const button=el('button',label);button.onclick=()=>{action();box.hidden=true};box.append(button)}box.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>box.hidden=true,action?10000:5500)}
function invalidateDownload(){document.querySelector('.export-controls a')?.remove();if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=null}
function fold(text){return String(text).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR').trim()}
function validIssued(){if(!$('issued').checkValidity()||!$('issued').value){toast('Escolha uma data válida para a emissão.');$('issued').reportValidity();$('issued').focus();return false}return true}
function editError(message,field){$('edit-error').textContent=message;$('edit-error').hidden=false;if(field)$(field).focus()}
function removeRecord(record){if(busy)return;invalidateDownload();const position=records.indexOf(record);records.splice(position,1);render();toast('Participação removida.',()=>{if(!records.includes(record)){records.splice(Math.min(position,records.length),0,record);invalidateDownload();render()}})}
async function api(path,payload){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok){const data=await response.json();throw Error(data.error||'Não foi possível processar os dados.')}return response}
function valid(r){return typeof r.name==='string'&&r.name.trim()&&r.name.length<=150&&/^\d{5,12}$/.test(r.ra)&&/^20\d{2}\.[12]$/.test(r.semester)&&typeof r.detail==='string'&&r.detail.trim()&&r.detail.length<=350&&Object.hasOwn(activities,r.activity)&&Number.isFinite(r.hours)&&r.hours>=0.5&&r.hours<=2000}
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node}
function downloadIcon(){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg'),path=document.createElementNS(ns,'path');svg.setAttribute('class','action-icon');svg.setAttribute('viewBox','0 0 20 20');svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','1.5');svg.setAttribute('stroke-linecap','round');svg.setAttribute('stroke-linejoin','round');svg.setAttribute('aria-hidden','true');path.setAttribute('d','M10 3v10m-4-4 4 4 4-4M4 14v3h12v-3');svg.append(path);return svg}
function render(){
 $('drop').setAttribute('aria-busy',String(busy));$('file').disabled=busy;['add','approve-ready','issued','naming'].forEach(id=>$(id).disabled=busy);
 $('people').textContent=new Set(records.map(r=>r.ra)).size;$('total').textContent=records.length;$('pending').textContent=records.filter(r=>r.warning||!valid(r)).length;
 const count=records.filter(r=>r.approved&&valid(r)&&!r.warning).length;$('approved').textContent=count;$('generate').disabled=busy||!count;$('export-note').textContent=`${count} certificado${count===1?'':'s'} aprovado${count===1?'':'s'} para emissão.`;
 const query=fold($('search').value),filter=$('filter').value;$('rows').replaceChildren();
 for(const r of records){if(!fold(`${r.name} ${r.ra}`).includes(query)||(filter==='pending'&&!r.warning&&valid(r))||(filter==='approved'&&!r.approved))continue;
  const tr=el('tr'),check=el('input');check.type='checkbox';check.checked=r.approved;check.disabled=busy;check.setAttribute('aria-label',`Aprovar ${r.name}, ${r.activity}, ${r.semester||'sem semestre'}`);check.onchange=()=>{if(!valid(r)||r.warning){check.checked=false;edit(r);return}r.approved=check.checked;invalidateDownload();render()};let td=el('td');td.append(check);tr.append(td);
  td=el('td',r.name);td.append(el('span',`RA ${r.ra}`,'sub'));tr.append(td);td=el('td',activities[r.activity]);td.append(el('span',r.detail,'sub'));tr.append(td);
  tr.append(el('td',r.semester||'A confirmar'),el('td',`${r.hours} h`));td=el('td');td.append(el('span',r.warning||!valid(r)?'Conferir':r.approved?'Aprovado':'Reconhecido',r.warning||!valid(r)?'badge warn':'badge'));tr.append(td);
  td=el('td');const editButton=el('button','Revisar');editButton.onclick=()=>edit(r);const preview=el('button','Prévia');preview.onclick=()=>showPreview(r);const remove=el('button','×');remove.setAttribute('aria-label',`Excluir participação de ${r.name}`);remove.onclick=()=>removeRecord(r);editButton.disabled=busy;preview.disabled=busy;remove.disabled=busy;td.append(editButton,preview,remove);tr.append(td);['Emitir','Participante / RA','Atividade','Semestre','Horas','Revisão','Ações'].forEach((label,i)=>tr.children[i].dataset.label=label);$('rows').append(tr);
 }
 if(!$('rows').children.length){const tr=el('tr',undefined,'empty-state'),td=el('td',records.length?'Nenhuma participação corresponde à busca ou ao filtro.':'O lote está vazio. Adicione uma participação ou importe outro arquivo.');td.colSpan=7;tr.append(td);$('rows').append(tr)}
}
async function upload(file){if(!file||busy)return;if(!/\.(csv|xlsx)$/i.test(file.name))return toast('Selecione um arquivo CSV ou XLSX.');if(file.size>10_000_000)return toast('O arquivo deve ter até 10 MB.');busy=true;render();$('upload-status').textContent='Lendo respostas e separando os semestres…';try{const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const data=await(await api('/api/analyze',{filename:file.name,data:btoa(binary)})).json();invalidateDownload();records=data.records;$('search').value='';$('filter').value='all';$('filename').textContent=file.name;$('review').hidden=false;$('step2').classList.add('active');$('step3').classList.remove('active');$('upload-status').textContent=`${data.responses} respostas importadas${data.duplicates?` · ${data.duplicates} duplicatas removidas`:''}.`;$('review').scrollIntoView({behavior:'smooth'});render()}catch(error){$('upload-status').textContent=error.message}finally{busy=false;$('file').value='';render()}}
$('file').onchange=event=>upload(event.target.files[0]);$('drop').ondragover=event=>{event.preventDefault();$('drop').classList.add('drag')};$('drop').ondragleave=()=> $('drop').classList.remove('drag');$('drop').ondrop=event=>{event.preventDefault();$('drop').classList.remove('drag');upload(event.dataTransfer.files[0])};
document.querySelector('label[for="file"]').addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&!busy){event.preventDefault();$('file').click()}});
function edit(record){if(busy)return;current=record;$('edit-error').hidden=true;$('source').textContent=record.source?`Resposta original (linha ${record.row}): ${record.source}\n${record.warning||''}`:'Nova participação';for(const key of ['name','ra','activity','detail','semester','hours'])$(`edit-${key}`).value=record[key];$('edit-approved').checked=record.approved;$('range-start').value='';$('range-end').value='';$('editor').showModal()}
$('close-editor').onclick=()=>$('editor').close();$('edit-form').onsubmit=event=>{event.preventDefault();const r={...current};for(const key of ['name','ra','activity','detail','semester'])r[key]=$(`edit-${key}`).value.trim();r.hours=Number($('edit-hours').value);r.approved=$('edit-approved').checked;r.warning='';const a=$('range-start').value,b=$('range-end').value;let semesters=[r.semester];if(a||b){if(!/^20\d{2}\.[12]$/.test(a)||!/^20\d{2}\.[12]$/.test(b))return editError('Preencha início e fim no formato 2026.1.','range-start');const index=s=>Number(s.slice(0,4))*2+Number(s.at(-1))-1;const start=index(a),end=index(b);if(end<start||end-start>40)return editError('Confira o intervalo: fim após início e máximo de 20 anos.','range-end');semesters=[];for(let i=start;i<=end;i++)semesters.push(`${Math.floor(i/2)}.${i%2+1}`)}if(!valid({...r,semester:semesters[0]}))return editError('Confira nome, RA, semestre, descrição e horas.','edit-semester');const position=records.indexOf(current);const added=semesters.map(s=>({...r,semester:s,id:crypto.randomUUID()}));if(position>=0)records.splice(position,1,...added);else records.push(...added);invalidateDownload();$('editor').close();render()};
$('add').onclick=()=>edit({name:'',ra:'',activity:'XII',detail:'',semester:'',hours:100,approved:false,source:'',row:''});$('search').oninput=render;$('filter').onchange=render;$('approve-ready').onclick=()=>{invalidateDownload();records.forEach(r=>{if(valid(r)&&!r.warning)r.approved=true});render();toast('Registros sem pendência aprovados. Confira a prévia antes de baixar.')};
async function showPreview(r){if(busy||!validIssued())return;if(!valid(r))return edit(r);try{const response=await api('/api/preview',{record:{...r,approved:true},issued:$('issued').value});if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(await response.blob());$('pdf-frame').src=previewUrl;$('open-pdf').href=previewUrl;$('preview').showModal()}catch(error){toast(error.message)}}
$('close-preview').onclick=()=>$('preview').close();
$('preview').addEventListener('close',()=>{$('pdf-frame').removeAttribute('src');$('open-pdf').removeAttribute('href');if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=null});
$('editor').addEventListener('close',()=>{current=null;$('edit-error').hidden=true});
$('issued').onchange=invalidateDownload;$('naming').onchange=invalidateDownload;
$('generate').onclick=async()=>{if(busy||!validIssued())return;busy=true;render();const button=$('generate');button.textContent='Gerando PDFs…';try{const approved=records.filter(r=>r.approved&&valid(r)&&!r.warning);if(approved.length>1000)throw Error('Emita até 1.000 certificados por lote. Desmarque registros para dividir a emissão.');const response=await api('/api/generate',{records:approved,issued:$('issued').value,naming:$('naming').value});if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=URL.createObjectURL(await response.blob());const a=el('a');a.href=downloadUrl;a.download=`XII-certificados-${$('issued').value}.zip`;a.textContent='Baixar ZIP gerado';a.append(downloadIcon());a.className='secondary download-link';document.querySelector('.export-controls a')?.remove();document.querySelector('.export-controls').append(a);a.click();$('step3').classList.add('active');toast(`${approved.length} certificado${approved.length===1?'':'s'} gerado${approved.length===1?'':'s'} com relatório de conferência.`)}catch(error){toast(error.message)}finally{busy=false;button.textContent='Baixar certificados .ZIP';button.append(downloadIcon());render()}};
$('help').onclick=()=>$('help-dialog').showModal();$('close-help').onclick=()=>$('help-dialog').close();
